version: "3.9"  # optional since v1.27.0
services:
  front:
    build: .
    container_name: kuorum-front
    environment:
      - API_DOMAIN=test-api.kuorum.org
      - MONGO_HOST=192.168.0.150
      - MONGO_PORT=27017
      - BUCKET_NAME=test-kuorumorg
      - UPLOADED_RESOURCES_DOMAIN=static-test.kuorum.org
      - STATICS_VERSION_PATH=/local/inaki
    ports:
      - 8080:8080



