version: "3.9"  # optional since v1.27.0
services:
  front:
    build: .
    container_name: kuorum-front
    environment
      - API_DOMAIN=local.kuorum.org
      - DATABASE_HOST=di15305-001.dbaas.ovh.net
      - DATABASE_PORT=35762
      - DATABASE_NAME=kuorum-test
      - DATABASE_USER=kuorum-api
      - DATABASE_PASSWORD=APIlecturaESCRITURA83
      - DATABASE_TYPE=mysql
      - MEMCACHE_URL=cache
      - MEMCACHE_PORT=11211
      - MONGO_HOST=192.168.0.150
      - SOLR_HOST=192.168.0.161
      - SOLR_PORT=8983
      - API_DOMAIN=local-api.kuorum.org
      - BUCKET_NAME=test-kuorumorg
      - UPLOADED_RESOURCES_DOMAIN=static-test.kuorum.org
    ports:
      - 8080:8080



