version: "3.9"  # optional since v1.27.0
services:
  memcached_front:
    image: bitnami/memcached
    mem_reservation: 16M
    restart: always
    container_name: memcached_front
    ports:
      - 11211:11211

  front:
#    depends_on:
    #      - memcached
    build:
      context: .
      args:
        VERSION: development
    container_name: kuorum-front
    env_file:
      - ./docker/env/local.env
    environment:
      - API_DOMAIN=kuorum-api:8443
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - BUCKET_NAME=static-kuorum-567923379073
      - UPLOADED_RESOURCES_DOMAIN=webcontent.dev.kuorum.org
    ports:
      - 8080:8080
      - 8443:8443

#networks:
#  default:
#    external:
#      name: kuorumservices_default



