version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USER: "DOCKERHUB:USERNAME"
    DOCKERHUB_PASS: "DOCKERHUB:PASS"
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo ---- INIT PRE BUILD -----
      - VERSION=`sed -n -e '/app.version/ s/.*\= *//p' application.properties`
#      - aws s3 cp s3://${DEPLOY_BUCKET}/grails-2.4.5.zip .
#      - unzip grails-2.4.5.zip

  build:
    commands:
      - echo ------- UPLOADING STATIC TO VERSION ${VERSION} -----------
      - ./grails-2.4.5/bin/grails -Dgrails.env=aws deployStatic
        -Dgraills.AMAZON_CDN_ENABLED=true
        -DPUBLIC_BUCKET_NAME=static-kuorum-${WORKING_ACCOUNT}
        -DBUCKET_REGION=eu-west-1
        -DSTATICS_VERSION_PATH=$VERSION
        -DUPLOADED_RESOURCES_DOMAIN=webcontent.${ENV}.kuorum.org
        --stacktrace
  post_build:
    commands:
      - echo ---- INIT POST BUILD ----

artifacts:
  files:
    - ./grails-2.4.5/**/*
#  discard-paths: yes
#  secondary-artifacts:
#    artifact1:
#      files:
#        - target/artifact-1.0.jar
#      discard-paths: yes
#    artifact2:
#      files:
#        - target/artifact-2.0.jar
