version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USER: "DOCKERHUB:USERNAME"
    DOCKERHUB_PASS: "DOCKERHUB:PASS"
phases:
  install:
    runtime-versions:
      java: openjdk8
    commnands:
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo '---- INIT PRE BUILD -----'
      - aws s3 cp s3://${DEPLOY_BUCKET}/grails-2.4.5.zip .
      - unzip grails-2.4.5.zip
      - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain kuorum-artifacts-domain --query authorizationToken --output text`
      - VERSION=`sed -n -e '/app.version/ s/.*\= *//p' application.properties`
      - CONTENT_DEPLOYED=`aws s3 ls s3://static-kuorum-567923379073/web/ | grep " $VERSION/"`
  build:
    commands:
      - echo '------- BUILD ${VERSION}-----------'
      - echo Build started on `date`
      - echo Downloading with maven
      - cd .aws
      - mvn -s settings.xml compile
      - cd ..
      - echo Initializing the proper compilation with grails
      - ./grails-2.4.5/bin/grails -Dgrails.env=aws war ROOT.war
  post_build:
    commands:
      - echo Deploying static content of ${VERSION}
      - |
        if [ -z "$CONTENT_DEPLOYED" ]; then
          ./grails-2.4.5/bin/grails -Dgrails.env=aws deployStatic \
            -Dgraills.AMAZON_CDN_ENABLED=true \
            -DPUBLIC_BUCKET_NAME=static-kuorum-${WORKING_ACCOUNT} \
            -DBUCKET_REGION=eu-west-1 \
            -DSTATICS_VERSION_PATH=$VERSION \
            -DUPLOADED_RESOURCES_DOMAIN=webcontent.${ENV}.kuorum.org \
            --stacktrace;
        else
          echo Skiped upload content. Version ${VERSION} already deployed
        fi;


artifacts:
  files:
    - ./docker/**/*
    - ./Dockerfile
    - ./ROOT.war
#    - ./grails-2.4.5/**/*
#    - ./.m2/**/*
    - .aws/*
    - application.properties
#  discard-paths: yes
#  secondary-artifacts:
#    artifact1:
#      files:
#        - target/artifact-1.0.jar
#      discard-paths: yes
#    artifact2:
#      files:
#        - target/artifact-2.0.jar
#      discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
