version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USER: "DOCKERHUB:USERNAME"
    DOCKERHUB_PASS: "DOCKERHUB:PASS"
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo '---- INIT PRE BUILD -----'
      - aws s3 cp s3://${DEPLOY_BUCKET}/grails-2.4.5.zip
      - unzip grails-2.4.5.zip
  build:
    commands:
      - echo '------- BUILD -----------'
      - echo Build started on `date`
      - grails-2.4.5/bin/grails -Dgrails.env=aws war ROOT.war
  post_build:
    commands:
      - echo '---- INIT POST BUILD ----'

artifacts:
  files:
    - ./docker/**/*
    - .aws/*
    - ./kuorumRest/Dockerfile
    - ./kuorumRest/docker/**/*
    - ./kuorumRest/target/kuorumRest.war
#  discard-paths: yes
#  secondary-artifacts:
#    artifact1:
#      files:
#        - target/artifact-1.0.jar
#      discard-paths: yes
#    artifact2:
#      files:
#        - target/artifact-2.0.jar
#      discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
