version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: "DOCKERHUB:USERNAME"
    DOCKERHUB_PASS: "DOCKERHUB:PASS"
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$WORKING_ACCOUNT
      - AWS_DEFAULT_REGION=$AWS_REGION
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
      - IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/kuorum/front:latest
      - VERSION=`sed -n -e '/app.version/ s/.*\= *//p' application.properties`
      - MEMCACHED_END_POINT=$MEMCACHED_END_POINT
      - MEMCACHED_PORT=$MEMCACHED_PORT
  build:
    commands:
      - echo Build started on `date`
      - sed -i "s/__MEMCACHED_END_POINT__/${MEMCACHED_END_POINT}/" ./docker/setenv.sh
      - sed -i "s/__MEMCACHED_PORT__/${MEMCACHED_PORT}/" ./docker/setenv.sh
      - docker build --build-arg VERSION=${VERSION} -t kuorum/front .
      - docker tag kuorum/front:latest $IMAGE_URI

  post_build:
    commands:
      - echo  Pushing image in the region ${AWS_DEFAULT_REGION} of the account $AWS_ACCOUNT_ID
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      # If we want to add more tags => - docker push --all-tags $IMAGE_URI
      - docker push $IMAGE_URI
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_CONTAINER $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
