
var dbDest = dbDest || connect("localhost:27017/Kuorum");

var Europe = dbDest.region.find({iso3166_2:"EU"}).next();
var Africa = dbDest.region.find({iso3166_2:"AF"}).next();
var NORTH_AMERCIA = dbDest.region.find({iso3166_2:"NA"}).next();

var SA = {
    "iso3166_2" : "SA",
    "name" : "South America",
    "postalCodes" : [ ],
    "regionType" : "SUPRANATIONAL"
}

dbDest.region.save(SA);
var SOUTH_AMERCIA = dbDest.region.find({iso3166_2:"SA"}).next();

var AS = {
    "iso3166_2" : "AS",
    "name" : "Asia",
    "postalCodes" : [ ],
    "regionType" : "SUPRANATIONAL"
}

dbDest.region.save(AS);
var ASIA = dbDest.region.find({iso3166_2:"AS"}).next();

var OC = {
    "iso3166_2" : "OC",
    "name" : "Oceania",
    "postalCodes" : [ ],
    "regionType" : "SUPRANATIONAL"
}

dbDest.region.save(OC);
var Oceania = dbDest.region.find({iso3166_2:"OC"}).next();

var AQ = {
    "iso3166_2" : "AQ",
    "name" : "Antarctica",
    "postalCodes" : [ ],
    "regionType" : "SUPRANATIONAL"
}

dbDest.region.save(AQ);
var Antarctica = dbDest.region.find({iso3166_2:"AQ"}).next();


var continents={
    "EU":Europe,
    "AF":Africa,
    "AS":ASIA,
    "NA":NORTH_AMERCIA,
    "SA":SOUTH_AMERCIA,
    "OC":Oceania,
    "AQ":Antarctica
}

var countries = [
    {name:"AALAND ISLANDS",continentCode:"EU", isoCode:"AX"},
    {name:"AFGHANISTAN",continentCode:"AS", isoCode:"AF"},
    {name:"ALBANIA",continentCode:"EU", isoCode:"AL"},
    {name:"ALGERIA",continentCode:"AF", isoCode:"DZ"},
    {name:"AMERICAN SAMOA",continentCode:"OC", isoCode:"AS"},
    {name:"ANDORRA",continentCode:"EU", isoCode:"AD"},
    {name:"ANGOLA",continentCode:"AF", isoCode:"AO"},
    {name:"ANGUILLA",continentCode:"NA", isoCode:"AI"},
    {name:"ANTARCTICA",continentCode:"AQ", isoCode:"AQ"},
    {name:"ANTIGUA AND BARBUDA",continentCode:"NA", isoCode:"AG"},
    {name:"ARGENTINA",continentCode:"SA", isoCode:"AR"},
    {name:"ARMENIA",continentCode:"EU", isoCode:"AM"},
    {name:"ARUBA",continentCode:"NA", isoCode:"AW"},
    {name:"AUSTRALIA",continentCode:"OC", isoCode:"AU"},
    {name:"AUSTRIA",continentCode:"EU", isoCode:"AT"},
    {name:"AZERBAIJAN",continentCode:"AS", isoCode:"AZ"},
    {name:"BAHAMAS",continentCode:"NA", isoCode:"BS"},
    {name:"BAHRAIN",continentCode:"AS", isoCode:"BH"},
    {name:"BANGLADESH",continentCode:"AS", isoCode:"BD"},
    {name:"BARBADOS",continentCode:"NA", isoCode:"BB"},
    {name:"BELARUS",continentCode:"EU", isoCode:"BY"},
    {name:"BELGIUM",continentCode:"EU", isoCode:"BE"},
    {name:"BELIZE",continentCode:"NA", isoCode:"BZ"},
    {name:"BENIN",continentCode:"AF", isoCode:"BJ"},
    {name:"BERMUDA",continentCode:"NA", isoCode:"BM"},
    {name:"BHUTAM",continentCode:"AS", isoCode:"BT"},
    {name:"BOLIVIA",continentCode:"SA", isoCode:"BO"},
    {name:"BOSNIA AND HERZEGOWINA",continentCode:"EU", isoCode:"BA"},
    {name:"BOTSWANA",continentCode:"AF", isoCode:"BW"},
    {name:"BOUVET ISLAND",continentCode:"AQ", isoCode:"BV"},
    {name:"BRAZIL",continentCode:"SA", isoCode:"BR"},
    {name:"BRITISH INDIAN OCEAN TERRITORY",continentCode:"AS", isoCode:"IO"},
    {name:"BRUNEI DARUSSALAM",continentCode:"AS", isoCode:"BN"},
    {name:"BULGARIA",continentCode:"EU", isoCode:"BG"},
    {name:"BURKINA FASO",continentCode:"AF", isoCode:"BF"},
    {name:"BURUNDI",continentCode:"AF", isoCode:"BI"},
    {name:"CAMBODIA",continentCode:"AS", isoCode:"KH"},
    {name:"CAMEROON",continentCode:"AF", isoCode:"CM"},
    {name:"CANADA",continentCode:"NA", isoCode:"CA"},
    {name:"CAPE VERDE",continentCode:"AF", isoCode:"CV"},
    {name:"CAYMAN ISLANDS",continentCode:"NA", isoCode:"KY"},
    {name:"CENTRAL AFRICAN REPUBLIC",continentCode:"AF", isoCode:"CF"},
    {name:"CHAD",continentCode:"AF", isoCode:"TD"},
    {name:"CHILE",continentCode:"SA", isoCode:"CL"},
    {name:"CHINA",continentCode:"AS", isoCode:"CN"},
    {name:"CHRISTMAS ISLAND",continentCode:"AS", isoCode:"CX"},
    {name:"COCOS (KEELING) ISLANDS",continentCode:"AS", isoCode:"CC"},
    {name:"COLOMBIA",continentCode:"SA", isoCode:"CO"},
    {name:"COMOROS",continentCode:"AF", isoCode:"KM"},
    {name:"Democratic republic of CONGO",continentCode:"AF", isoCode:"CD"},
    {name:"Republic of CONGO",continentCode:"AF", isoCode:"CG"},
    {name:"COOK ISLAND",continentCode:"OC", isoCode:"CK"},
    {name:"COSTA RICA",continentCode:"NA", isoCode:"CR"},
    {name:"COTE D'IVOIRE",continentCode:"AF", isoCode:"CI"},
    {name:"CROATIA",continentCode:"EU", isoCode:"HR"},
    {name:"CUBA",continentCode:"NA", isoCode:"CU"},
    {name:"CYPRUS",continentCode:"EU", isoCode:"CY"},
    {name:"CZECH REPUBLIC",continentCode:"EU", isoCode:"CZ"},
    {name:"DENMARK",continentCode:"EU", isoCode:"DK"},
    {name:"DJIBOUTI",continentCode:"AF", isoCode:"DJ"},
    {name:"DOMINICA",continentCode:"NA", isoCode:"DM"},
    {name:"DOMINICAN REPUBLIC",continentCode:"NA", isoCode:"DO"},
    {name:"ECUADOR",continentCode:"SA", isoCode:"EC"},
    {name:"EGYPT",continentCode:"AF", isoCode:"EG"},
    {name:"EL SALVADOR",continentCode:"NA", isoCode:"SV"},
    {name:"EQUATORIAL GUINEA",continentCode:"AF", isoCode:"GQ"},
    {name:"ERITREA",continentCode:"AF", isoCode:"ER"},
    {name:"ESTONIA",continentCode:"EU", isoCode:"EE"},
    {name:"ETHIOPIA",continentCode:"AF", isoCode:"ET"},
    {name:"MALVINAS",continentCode:"SA", isoCode:"FK"},
    {name:"FAROE ISLANDS",continentCode:"EU", isoCode:"FO"},
    {name:"FIJI",continentCode:"OC", isoCode:"FJ"},
    {name:"FINLAND",continentCode:"EU", isoCode:"FI"},
    {name:"FRANCE",continentCode:"EU", isoCode:"FR"},
    {name:"FRENCH GUIANA",continentCode:"SA", isoCode:"GF"},
    {name:"FRENCH POLYNESIA",continentCode:"OC", isoCode:"PF"},
    {name:"FRENCH SOUTHERN TERRITORIES",continentCode:"EU", isoCode:"TF"},
    {name:"GABON",continentCode:"AF", isoCode:"GA"},
    {name:"GAMBIA",continentCode:"AF", isoCode:"GM"},
    {name:"GEORGIA",continentCode:"EU", isoCode:"GE"},
    {name:"GERMANY",continentCode:"EU", isoCode:"DE"},
    {name:"GHANA",continentCode:"AF", isoCode:"GH"},
    {name:"GIBRALTAL",continentCode:"EU", isoCode:"GI"},
    {name:"GREECE",continentCode:"EU", isoCode:"GR"},
    {name:"GREENLAND",continentCode:"NA", isoCode:"GL"},
    {name:"GRENADA",continentCode:"NA", isoCode:"GD"},
    {name:"GUADELOUPE",continentCode:"NA", isoCode:"GP"},
    {name:"GUAM",continentCode:"OC", isoCode:"GU"},
    {name:"GUATEMALA",continentCode:"NA", isoCode:"GT"},
    {name:"GUINEA",continentCode:"AF", isoCode:"GN"},
    {name:"GHINEA-BISSAU",continentCode:"AF", isoCode:"GW"},
    {name:"GUYANA",continentCode:"SA", isoCode:"GY"},
    {name:"HAITI",continentCode:"NA", isoCode:"HT"},
    {name:"HEARD AND MC DONALD ISLANDS",continentCode:"OC", isoCode:"HM"},
    {name:"HONDURAS",continentCode:"NA", isoCode:"HN"},
    {name:"HONG KONG",continentCode:"AS", isoCode:"HK"},
    {name:"HUNGARY",continentCode:"EU", isoCode:"HU"},
    {name:"ICELAND",continentCode:"EU", isoCode:"IS"},
    {name:"INDIA",continentCode:"AS", isoCode:"IN"},
    {name:"INDONESIA",continentCode:"AS", isoCode:"ID"},
    {name:"IRAN (ISLAMIC REPUBLIC OF)",continentCode:"AS", isoCode:"IR"},
    {name:"IRAQ",continentCode:"AS", isoCode:"IQ"},
    {name:"IRELAND",continentCode:"EU", isoCode:"IE"},
    {name:"ISRAEL",continentCode:"AS", isoCode:"IL"},
    {name:"ITALY",continentCode:"EU", isoCode:"IT"},
    {name:"JAMAICA",continentCode:"NA", isoCode:"JM"},
    {name:"JAPAN",continentCode:"AS", isoCode:"JP"},
    {name:"JORDAN",continentCode:"AS", isoCode:"JO"},
    {name:"KAZAKHSTAN",continentCode:"AS", isoCode:"KZ"},
    {name:"KENYA",continentCode:"AF", isoCode:"KE"},
    {name:"KIRIBATI",continentCode:"OC", isoCode:"KI"},
    {name:"North Korea",continentCode:"AS", isoCode:"KP"},
    {name:"South Korea",continentCode:"AS", isoCode:"KR"},
    {name:"KUWAIT",continentCode:"AS", isoCode:"KW"},
    {name:"KYRGYZSTAN",continentCode:"AS", isoCode:"KG"},
    {name:"LAO",continentCode:"AS", isoCode:"LA"},
    {name:"LATVIA",continentCode:"EU", isoCode:"LV"},
    {name:"LEBANON",continentCode:"AS", isoCode:"LB"},
    {name:"LESOTHO",continentCode:"AF", isoCode:"LS"},
    {name:"LIBERIA",continentCode:"AF", isoCode:"LR"},
    {name:"LIByAN ARAB JAMAHIRIYA",continentCode:"AF", isoCode:"LY"},
    {name:"LIECHTENSTEIN",continentCode:"EU", isoCode:"LI"},
    {name:"LITHUANIA",continentCode:"EU", isoCode:"LT"},
    {name:"LUXEMBOURG",continentCode:"EU", isoCode:"LU"},
    {name:"MACAU",continentCode:"AS", isoCode:"MO"},
    {name:"MACEDONIA",continentCode:"EU", isoCode:"MK"},
    {name:"MADAGASCAR",continentCode:"AF", isoCode:"MG"},
    {name:"MALAWI",continentCode:"AF", isoCode:"MW"},
    {name:"MALAYSIA",continentCode:"AS", isoCode:"MY"},
    {name:"MALDIVES",continentCode:"AS", isoCode:"MV"},
    {name:"MALI",continentCode:"AF", isoCode:"ML"},
    {name:"MALTA",continentCode:"EU", isoCode:"MT"},
    {name:"MARSHALL ISLANDS",continentCode:"OC", isoCode:"MH"},
    {name:"MARTINIQUE",continentCode:"NA", isoCode:"MQ"},
    {name:"MAURITANIA ",continentCode:"AF", isoCode:"MR"},
    {name:"MAURITIUS",continentCode:"AF", isoCode:"MU"},
    {name:"MAYOTTE",continentCode:"AF", isoCode:"YT"},
    {name:"MEXICO",continentCode:"NA", isoCode:"MX"},
    {name:"MICORENISA",continentCode:"OC", isoCode:"FM"},
    {name:"REPUBLIC OF MOLDOVA",continentCode:"EU", isoCode:"MD"},
    {name:"MONACO",continentCode:"EU", isoCode:"MC"},
    {name:"MONGOLIA",continentCode:"AS", isoCode:"MN"},
    {name:"MONTSERRAT",continentCode:"NA", isoCode:"MS"},
    {name:"MOROCCO",continentCode:"AF", isoCode:"MA"},
    {name:"MOZAMBIQUE",continentCode:"AF", isoCode:"MZ"},
    {name:"MYANMAR",continentCode:"AS", isoCode:"MM"},
    {name:"NAMIBIA",continentCode:"AF", isoCode:"NA"},
    {name:"NAURU",continentCode:"OC", isoCode:"NR"},
    {name:"NEPAL",continentCode:"AS", isoCode:"NP"},
    {name:"NETHERLANDS",continentCode:"EU", isoCode:"NL"},
    {name:"NETHERLANDS ANTILLES ",continentCode:"EU", isoCode:"AN"},
    {name:"NEW CALEDONIA",continentCode:"OC", isoCode:"NC"},
    {name:"NEW ZEALAND",continentCode:"OC", isoCode:"NZ"},
    {name:"NICARAGUA",continentCode:"NA", isoCode:"NI"},
    {name:"NIGER",continentCode:"AF", isoCode:"NE"},
    {name:"NIGERIA",continentCode:"AF", isoCode:"NG"},
    {name:"NIUE",continentCode:"OC", isoCode:"UN"},
    {name:"NORFOLK ISLAND",continentCode:"OC", isoCode:"NF"},
    {name:"NORTHERN MARIANA ISLANDS",continentCode:"OC", isoCode:"MP"},
    {name:"NORWAY",continentCode:"EU", isoCode:"NO"},
    {name:"OMAN",continentCode:"AS", isoCode:"OM"},
    {name:"PAKISTAN",continentCode:"AS", isoCode:"PK"},
    {name:"PALAU",continentCode:"OC", isoCode:"PW"},
    {name:"PALESTINIAN",continentCode:"AS", isoCode:"PS"},
    {name:"PANAMA",continentCode:"NA", isoCode:"PA"},
    {name:"PAPUA NEW GUINEA",continentCode:"OC", isoCode:"PG"},
    {name:"PARAGUAY",continentCode:"SA", isoCode:"PY"},
    {name:"PERU",continentCode:"SA", isoCode:"PE"},
    {name:"PHILIPPINES",continentCode:"AS", isoCode:"PH"},
    {name:"PITCAIRN",continentCode:"OC", isoCode:"PN"},
    {name:"POLAND",continentCode:"EU", isoCode:"PL"},
    {name:"PORTUGAL",continentCode:"EU", isoCode:"PT"},
    {name:"PUERTO RICO",continentCode:"NA", isoCode:"PR"},
    {name:"QATAR",continentCode:"AS", isoCode:"QA"},
    {name:"REUNION",continentCode:"AF", isoCode:"RE"},
    {name:"ROMANIA",continentCode:"EU", isoCode:"RO"},
    {name:"RUSSIAN FEDERATION ",continentCode:"EU", isoCode:"RU"},
    {name:"RWANDA",continentCode:"AF", isoCode:"RW"},
    {name:"SAINT HELENA ",continentCode:"AF", isoCode:"SH"},
    {name:"SAINT KITTS AND NEVIS",continentCode:"NA", isoCode:"KN"},
    {name:"SAINT LUCIA",continentCode:"NA", isoCode:"LC"},
    {name:"SAINT PIERRE AND MIQUELON",continentCode:"NA", isoCode:"PM"},
    {name:"SAINT VINCENT AND THE GRENADINES",continentCode:"NA", isoCode:"VC"},
    {name:"SAMOA",continentCode:"OC", isoCode:"WS"},
    {name:"SAN MARINO",continentCode:"EU", isoCode:"SM"},
    {name:"SAO TOME AND PRINCIPE",continentCode:"AF", isoCode:"ST"},
    {name:"SAUDI ARABIA",continentCode:"AS", isoCode:"SA"},
    {name:"SENEGAL",continentCode:"AF", isoCode:"SN"},
    {name:"SERBIA AND MONTENEGRO",continentCode:"EU", isoCode:"CS"},
    {name:"SEYCHELLES",continentCode:"AF", isoCode:"SC"},
    {name:"SIERRA LEONE",continentCode:"AF", isoCode:"SL"},
    {name:"SINGAPURE",continentCode:"AS", isoCode:"SG"},
    {name:"SLOVAKIA",continentCode:"EU", isoCode:"SK"},
    {name:"SLOVENIA",continentCode:"EU", isoCode:"SI"},
    {name:"SOLOMON ISLANDS",continentCode:"OC", isoCode:"SB"},
    {name:"SOMALIA",continentCode:"AF", isoCode:"SO"},
    {name:"SOUTH AFRICA",continentCode:"AF", isoCode:"ZA"},
    {name:"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",continentCode:"AQ", isoCode:"GS"},
    {name:"SPAIN",continentCode:"EU", isoCode:"ES"},
    {name:"SRI LANKA",continentCode:"AS", isoCode:"LK"},
    {name:"SUDAN",continentCode:"AF", isoCode:"SD"},
    {name:"SRINAME",continentCode:"SA", isoCode:"SR"},
    {name:"SVALBARD AND JAN MAYEN ISLANDS",continentCode:"EU", isoCode:"SJ"},
    {name:"SWAZILAND",continentCode:"AF", isoCode:"SZ"},
    {name:"SWEDEN",continentCode:"EU", isoCode:"SE"},
    {name:"SWITZERLAND",continentCode:"EU", isoCode:"CH"},
    {name:"SYRIAN ARAB REPUBLIC",continentCode:"AS", isoCode:"SY"},
    {name:"TAIWAN",continentCode:"AS", isoCode:"TW"},
    {name:"TAJIKISTAN",continentCode:"AS", isoCode:"TJ"},
    {name:"TANZANIA",continentCode:"AF", isoCode:"TZ"},
    {name:"THAILAND",continentCode:"AS", isoCode:"TH"},
    {name:"TIMOR-LESTE",continentCode:"AS", isoCode:"TL"},
    {name:"TOGO",continentCode:"AF", isoCode:"TG"},
    {name:"TOKELAU",continentCode:"OC", isoCode:"TK"},
    {name:"TONGA",continentCode:"OC", isoCode:"TO"},
    {name:"TRINIDAD AND TOBAGO",continentCode:"NA", isoCode:"TT"},
    {name:"TUNISIA",continentCode:"AF", isoCode:"TN"},
    {name:"TURKEY",continentCode:"EU", isoCode:"TR"},
    {name:"TURKMENISTAN",continentCode:"AS", isoCode:"TM"},
    {name:"TURKS AND CAICOS ISLAND",continentCode:"NA", isoCode:"TC"},
    {name:"TUVALU",continentCode:"OC", isoCode:"TV"},
    {name:"UGANDA",continentCode:"AF", isoCode:"UG"},
    {name:"UKRAINE",continentCode:"EU", isoCode:"UA"},
    {name:"UNITED ARAB EMIRATES",continentCode:"AS", isoCode:"AE"},
    {name:"UNITED KINDOM",continentCode:"EU", isoCode:"GB"},
    {name:"UNITED STATES",continentCode:"NA", isoCode:"US"},
    {name:"UNITED STATES MINOR OUTLYING ISLAND",continentCode:"NA", isoCode:"UM"},
    {name:"URUGUAY",continentCode:"SA", isoCode:"UY"},
    {name:"UZBEKISTAN",continentCode:"AS", isoCode:"UZ"},
    {name:"VANUATU",continentCode:"OC", isoCode:"VU"},
    {name:"VATICAN CITY STATE (HOLY SEE)",continentCode:"EU", isoCode:"VA"},
    {name:"VENEZUELA",continentCode:"SA", isoCode:"VE"},
    {name:"VIET NAM",continentCode:"AS", isoCode:"VN"},
    {name:"VIRGIN ISLANDS (BRITISH)",continentCode:"EU", isoCode:"VG"},
    {name:"VIRGIN ISLAND (U.S)",continentCode:"NA", isoCode:"VI"},
    {name:"WALLIS AND FUTUNA ISLANDS",continentCode:"OC", isoCode:"WF"},
    {name:"WESTERN SAHARA ",continentCode:"AF", isoCode:"EH"},
    {name:"YEMEN",continentCode:"AS", isoCode:"YE"},
    {name:"ZAMBIA",continentCode:"AF", isoCode:"ZM"},
    {name:"ZIMBABWE",continentCode:"AF", isoCode:"ZW"}
]

function toTitleCase(str){
    return str.replace(/\w\S*/g, function(txt){return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();});
}

countries.forEach(function(country){

    print(country.continentCode +"-"+country.isoCode)
    var continent = continents[country.continentCode]
    var region ={
        "iso3166_2" : country.continentCode +"-"+country.isoCode,
        "name" : toTitleCase(country.name),
        "superRegion" : continent._id,
        "version" : 0,
        "postalCodes" : [],
        "regionType": "NATION"
    }
    dbDest.region.save(region)
})